[package]
name = "dataloader"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bincode = "2.0.1"
dama.workspace = true
dataformat = { version = "0.1.0", path = "../dataformat" }
rand = "0.9.0"
